namespace Elythia
{
    public enum StatusEffectType
    {
        None,
        Burn,
        Slow,
        Stun,
        Bleed,
        Silence,
        Sleep,
        Freeze,
        Paralyze,
        Stasis,
        Poison,
        Blind,
        Fear,
        Confuse,
        AttackSpeed,
        SpellSize,
        Invincibility,
        PickupDropRateBoost,
        ItemDropRateBoost,
        PickupRadiusBoost,
        ArmorBoost,
        HazardBlock,
        JumpBoost,
        DashDistanceBoost,
        MoveSpeedBoost,
        HealthOverTime,
        MaxHealthRegen,
        MaxHealthSurge,
        ManaOverTime,
        MaxManaRegen,
        MaxManaSurge,
        Invisibility
    }
}